version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=haemoUser
      - POSTGRES_PASSWORD=Aht123786
      - POSTGRES_DB=docker_tests

  web:
    build: .
    command: bash -c 'python manage.py runserver 0.0.0.0:8000'
    volumes:
      - .:/haemo_support_backend
    ports:
      - "8000:8000"
    env_file:
      - ./env.txt
    depends_on:
      - db
