name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - "**"

jobs:
  run_tests:
    name: Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        python-version: ["3.9"]
        toxenv: [django31, django32, quality]

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install pipenv
        run: pip install pipenv

      - name: Install Dependencies
        run: pipenv install

      - name: Install Dev Dependencies
        run: pipenv install --dev

      - name: Run Quality Checks
        env:
          TOXENV: ${{ matrix.toxenv }}
        run: pipenv run tox
